select TABLE_SCHEMA,TABLE_NAME,REBALANCE_METHOD,DURATION_SEC as durSEC,SEPARATED_PERCENT as 'SEPARATED%',TRANSFERRED_PERCENT as 'TRANSF%'
,(SEPARATED_BYTES/1024/1024)::int SEPARATED_MB,(TO_SEPARATE_BYTES/1024/1024)::int as TO_SEPARATE_MB
,(TRANSFERRED_BYTES/1024^2)::int as TRANSF_MB,(TO_TRANSFER_BYTES/1024^2)::int as TO_TRANSF_MB
,IS_LATEST
from REBALANCE_TABLE_STATUS
where --elastic_cluster_version = (SELECT version FROM v_catalog.elastic_cluster)
(SEPARATED_PERCENT < 100 or TRANSFERRED_PERCENT < 100)
order by SEPARATED_PERCENT desc ,TRANSFERRED_PERCENT desc 
