\timing 

\echo FACT_ENGAGEMENT
COPY lp_15744040."FACT_ENGAGEMENT"
(ENG_LP_SESSION_ID,VS_LP_SESSION_ID,IMD_LP_SESSION_ID,IMR_LP_SESSION_ID,QUEUE_LP_SESSION_ID,ACCOUNT_ID,LP_ACCOUNT_ID,AGENT_ID,LP_AGENT_ID,ROOM_ID,CHANNEL_ID,APPROACH_TYPE_ID,END_REASON_ID,
IMPRESSION_OBJECT_ID,VISIT_FROM_DT_TRUNC,VISIT_FROM_DT_ACTUAL,VISIT_TO_DT_ACTUAL,ENG_FROM_DT_TRUNC,ENG_FROM_DT_ACTUAL,ENG_TO_DT_ACTUAL,ENTER_QUEUE_DT_ACTUAL,END_QUEUE_DT_ACTUAL,EXIT_SURVEY_VIEW_DT_ACTUAL,
EXIT_SURVEY_FILLED_DT_ACTUAL,DURATION,CSAT_SCORE,INTERACTIVE_IND,HOT_LEAD_IND,EXIT_SURVEY_VIEW_IND,EXIT_SURVEY_FILLED_IND)
FROM '/hdfs/vvpt-mha01/user/dataint/poc/20120119-063904/Eng/Eng*' DELIMITER ',' DIRECT;


\echo FACT_INSESSION_CONVERSION
COPY lp_15744040."FACT_INSESSION_CONVERSION"
(CONV_LP_SESSION_ID,VS_LP_SESSION_ID,IMD_LP_SESSION_ID,IMR_LP_SESSION_ID,QUEUE_LP_SESSION_ID,ENG_LP_SESSION_ID,CREDIT_ALGORITHM_ID,ACCOUNT_ID,
LP_ACCOUNT_ID,AGENT_ID,LP_AGENT_ID,CHANNEL_ID,ROOM_ID,APPROACH_TYPE_ID,CONVERSION_DEF_ID,IMPRESSION_OBJECT_ID,CONV_DT_TRUNC,CONV_DT_ACTUAL,
VISIT_FROM_DT_TRUNC,VISIT_FROM_DT_ACTUAL,VISIT_TO_DT_ACTUAL,ORDER_NUMBER,CONVERSION_VALUE,CONVERSION_RATIO,HOT_LEAD_IND,SELF_SERVICE_IND)
FROM '/hdfs/vvpt-mha01/user/dataint/poc/20120119-063904/Conv/Conv*' DELIMITER ',' DIRECT;


\echo FACT_VISIT
COPY lp_15744040."FACT_VISIT"
(VS_LP_SESSION_ID,VS_LP_VISITOR_ID,ACCOUNT_ID,LP_ACCOUNT_ID,VISIT_FROM_DT_TRUNC, VISIT_FROM_DT_ACTUAL, VISIT_TO_DT_ACTUAL,HOT_LEAD_IND )
FROM '/hdfs/vvpt-mha01/user/dataint/poc/20120119-063904/Visit/Visit*' DELIMITER ',' DIRECT;

\echo FACT_VISIT_ROOM

COPY lp_15744040."FACT_VISIT_ROOM"
(VS_LP_SESSION_ID,ROOM_ID,VS_LP_VISITOR_ID,ACCOUNT_ID,LP_ACCOUNT_ID,VISIT_FROM_DT_TRUNC,VISIT_FROM_DT_ACTUAL,VISIT_TO_DT_ACTUAL,HOT_LEAD_IND)
FROM '/hdfs/vvpt-mha01/user/dataint/poc/20120119-063904/VisitRoom/VisitRoom*' DELIMITER ',' DIRECT;

\echo FACT_IMD

COPY lp_15744040."FACT_IMD"
(IMD_LP_SESSION_ID,VS_LP_SESSION_ID,APPROACH_TYPE_ID,ACCOUNT_ID,LP_ACCOUNT_ID,CHANNEL_ID,IMPRESSION_OBJECT_ID,ROOM_ID,VISIT_FROM_DT_TRUNC,VISIT_FROM_DT_ACTUAL,VISIT_TO_DT_ACTUAL,IMD_DT_ACTUAL,HOT_LEAD_IND)
FROM '/hdfs/vvpt-mha01/user/dataint/poc/20120119-063904/Imd/Imd*' DELIMITER ',' DIRECT;


\echo FACT_IMR

COPY lp_15744040."FACT_IMR"
(IMR_LP_SESSION_ID,VS_LP_SESSION_ID,IMD_LP_SESSION_ID,APPROACH_TYPE_ID,ACCOUNT_ID,LP_ACCOUNT_ID,CHANNEL_ID,IMPRESSION_OBJECT_ID,ROOM_ID,RESPONSE_ID,VISIT_FROM_DT_TRUNC,VISIT_FROM_DT_ACTUAL,VISIT_TO_DT_ACTUAL,IMR_DT_ACTUAL,HOT_LEAD_IND)
FROM '/hdfs/vvpt-mha01/user/dataint/poc/20120119-063904/Imr/Imr*' DELIMITER ',' DIRECT;



\echo FACT_AGENT_SESSION

COPY lp_15744040."FACT_AGENT_SESSION"
(LP_AGENT_SESSION_ID,ACCOUNT_ID,LP_ACCOUNT_ID,AGENT_ID,LP_AGENT_ID,CHANNEL_ID,AGENT_STATUS_ID,FROM_DT_TRUNC,FROM_DT_ACTUAL,TO_DT_ACTUAL,DURATION,CONCURRENT_ENG)
FROM '/hdfs/vvpt-mha01/user/dataint/poc/20120122-031910/Agent/Agent*' DELIMITER ',' DIRECT;
